### PR TITLE
add in a debounce to try to ensure changes have been triggered from bind...

### PR DESCRIPTION
**Pull request by smmullen90**
...ings

### CODE REVIEW

**Comment by mnelson** [comment]
I'm still not convinced a debounce is the right thing. What do you think about a function which reads all the bindings to ensure the model is up to date?

```js
this.readBindings(function() {
  this.validateAll(function(){
  });
});
```

**Comment by smmullen90** [comment]
maybe we can pair on doing that. i just didnt really know how to get all the bindings to work correctly. was trying to hook into binding.toModel but that was really janky

**Comment by smmullen90** [comment]
i could have been silly in how i was trying to implement though.

**Comment by mnelson** [comment]
#7 handles this.

**Pull request closed without merging**
